services:
  # elasticsearch:
  #   image: elasticsearch:7.17.0
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - ./elasticsearch:/usr/share/elasticsearch/data
  # kibana:
  #   image: kibana:7.17.0
  #   container_name: kibana
  #   environment:
  #     ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch
  # logstash:
  #   image: logstash:7.17.0
  #   container_name: logstash
  #   volumes:
  #     - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #     - ./nginx_logs:/var/log/nginx
  #     - ./backend_logs:/var/log/backend
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - elasticsearch
  frontend:
    image: frontend
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /code
    restart: always
    volumes:
      - ./frontend:/code
      - ./static_volume:/code/staticfiles
    env_file:
      - .env
    depends_on:
      - elasticsearch
  logstash:
    image: logstash:7.17.0
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./nginx_logs:/var/log/nginx
      - ./backend_logs:/var/log/backend
    ports:
      - "5000:5000"
    depends_on:
      frontend_db:
        condition: service_healthy
  nginx:
    image: nginx:1.19
    container_name: nginx
    ports:
      - "8005:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/code
      - ./certs/nginx:/etc/nginx/ssl
      - ./static_volume:/static
    depends_on:
      - login_backend
      - frontend
      - tournament
  login_db:
    image: postgres:12
    container_name: login_db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "8004:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 10
      start_period: 2s
    volumes:
      - ./postgres:/var/lib/postgresql/data
  frontend_db:
    image: postgres:12
    container_name: frontend_db
    environment:
      POSTGRES_USER: $POSTGRES_USER2
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD2
      POSTGRES_DB: $POSTGRES_DB2
    ports:
      - "8008:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 10
      start_period: 2s
  tournament_db:
    image: postgres:12
    container_name: tournament_db
    environment:
      POSTGRES_USER: $POSTGRES_USER3
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD3
      POSTGRES_DB: $POSTGRES_DB3
    ports:
      - "8009:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 10
      start_period: 2s
  login_backend:
    image: login_backend
    container_name: login_backend
    build: 
      context: ./login
      dockerfile: Dockerfile
    working_dir: /code
    restart: always
    volumes:
      - ./login:/code
      - ./backend_logs:/code/logs
    env_file:
      - .env
    depends_on:
      login_db:
        condition: service_healthy
  tournament:
    image: tournament
    container_name: tournament
    build: 
      context: ./tournament
      dockerfile: Dockerfile
    working_dir: /code
    restart: always
    volumes:
      - ./tournament:/code
      - ./backend_logs:/code/logs
    env_file:
      - .env
    ports:
      - "8007:8007"
    depends_on:
      tournament_db:
        condition: service_healthy

  
networks:
  default:
      driver: bridge