services:
  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/code
    depends_on:
      - login_backend
  login_db:
    image: postgres:12
    container_name: login_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 10
      start_period: 2s
    volumes:
      - ./postgres:/var/lib/postgresql/data
  login_backend:
    image: login_backend
    container_name: login_backend
    build: 
      context: ./login
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    working_dir: /code
    restart: always
    volumes:
      - ./login:/code
    depends_on:
      login_db:
        condition: service_healthy
networks:
  default:
      driver: bridge